// <auto-generated />
namespace Repo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class message : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221713532_message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
